[package]
name = "saltbot"
version = "0.1.0"
authors = ["Kristopher Bullinger <kris.bullinger@gmx.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = { version = "0.9", default-features = false, features = ["client", "gateway", "rustls_backend", "model"] }
# serenity = "0.9"
tokio = { version = "0.2", features = ["macros"] }
rand = "0.8.3"
chrono = "0.4.19"
image = "0.23.14"
imageproc = "0.22.0"
rusttype = "0.9.2"
percent-encoding = "2.1.0"
